business:
  name: Founder Funnel
  legalName: Incubrain Pvt. Ltd.
  foundingYear: 2023
  logo: /favicon-96x96.png
  mission: We help technical founders reach inner peace and financial freedom.
socials:
  x: https://x.com/DrewMacGibbon
  youtube: https://www.youtube.com/@DrewMacGibbon
  github: https://github.com/Drew-Macgibbon
