layout:
  banner:
    sticky: true
    offer: mentorship
  navbar:
    sticky: false
  footer:
    offer: mentorship

main:
  - label: About
    to: /about
  - label: Mentorship
    to: /offers/mentorship

footerLinks:
  - label: About
    children:
      - label: Our Story
        to: /about
      - label: Decisions
        to: /decisions
      - label: Roadmap
        to: https://github.com/incubrain/founder-funnel/discussions/133
  - label: Offers
    children:
      - label: Mentorship
        to: /offers/mentorship
