banner:
  id: hiring-2026
  icon: i-lucide-info
  title: We're hiring! Check out our open positions at Astronera.
  actions:
    - label: Careers
      to: https://careers.astronera.org
      target: _blank
      trailingIcon: i-lucide-arrow-right
      color: primary
      variant: solid
      size: xs
  close: true
  color: primary
  ui: {}
footer:
  columns:
    - label: Research
      icon: i-lucide-flask-conical
      to: /darksky/research
      children:
        - label: Overview
          to: /darksky/research
        - label: Ecology & Biodiversity
          to: /darksky/research/ecology
        - label: Human Health
          to: /darksky/research/health
        - label: Climate Change
          to: /darksky/research/climate
        - label: Tourism
          to: /darksky/research/tourism
    - label: Policy
      icon: i-lucide-book-open
      to: /darksky/policy
      children:
        - label: Overview
          to: /darksky/policy
        - label: Global Presedents
          to: /darksky/policy/global-presedents
        - label: Legal Obligations
          to: /darksky/policy/legal-obligations
        - label: Departmental Actions
          to: /darksky/policy/departmental-actions
        - label: Regulatory Framework
          to: /darksky/policy/regulatory-framework
        - label: Recommendations
          to: /darksky/policy/recommendations
        - label: Technical Secretariat
          to: /darksky/policy/technical-secretariat
    - label: Pilots
      icon: i-lucide-book-key
      to: /darksky/pilots
      children:
        - label: Overview
          to: /darksky/pilots
    - label: Resources
      icon: i-lucide-book-key
      to: /resources
      children:
        - label: Sources
          icon: i-lucide-file-pen-line
          to: /resources/sources
        - label: Glossary
          icon: i-lucide-library
          to: /resources/glossary
  bottom: []
header:
  title: AstronEra
  socials:
    x: https://x.com/AstronEra
  navigation:
    - label: Dark Sky
      icon: i-lucide-moon
      to: /darksky
      children:
        - label: Research
          icon: i-lucide-flask-conical
          to: /darksky/research
          description: add more details
        - label: Policy
          icon: i-lucide-book-open
          to: /darksky/policy
        - label: Pilots
          icon: i-lucide-sprout
          to: /darksky/pilots
    - label: Resources
      icon: i-lucide-book-key
      to: /resources
      children:
        - label: Sources
          icon: i-lucide-file-pen-line
          to: /resources/sources
        - label: Glossary
          icon: i-lucide-library
          to: /resources/glossary
  showSearch: true
  showColorMode: true
