layout:
  banner:
    sticky: true
    offer: certification
  navbar:
    sticky: false
  footer:
    offer: certification

main:
  - label: About
    to: /about
  - label: Content
    to: https://content.astronera.org

footerLinks:
  - label: About
    children:
      - label: Our Story
        to: /about
      - label: Content
        to: https://content.astronera.org
  - label: Resources
    children:
      - label: FAQ
        to: /#faq
      - label: Contact
        to: mailto:connectus@astronera.org
